[package]
name = "xcp"
version = "0.1.0"
authors = ["Steve Smith <tarkasteve@gmail.com>"]
edition = "2018"

[features]
default = ["kernel_copy_file_range"]
kernel_copy_file_range = []

[dependencies]
libc = "0.2"
log = "0.4"
simplelog = "0.5"
failure = "0.1"
clap = "2"
structopt = "0.2"
walkdir = "2"
ignore = "0.4"

[dev-dependencies]
tempfile = "3"
escargot = "0.3"
uuid = { version="0.7", features=["v4"]}
